[default]
O = "A"
E = "A"
T = "C"
W = "C"
S = "S"
R = "S"

page_up = "PUp"
page_down = "PDown"
home = "Home"
end = "End"

up_arrow = "Up"
down_arrow = "Down"
left_arrow = "Left"
right_arrow = "Right"

left_shift = "<S>"
left_control = "<T>"
left_option = "<O>"
left_command = "<C>"

right_shift = "<R>"
right_control = "<W>"
right_option = "<E>"
right_command = "<Q>"

tab = "TAB"
delete_or_backspace = "DEL"
return_or_enter = "RET"
caps_lock = "<P>"
spacebar = "<_>"

hyphen = "-"
equal_sign = "="
open_bracket = "["
close_bracket = "]"
semicolon = ";"
quote = "'"
backslash = "\\"
comma = ","
period = "."
slash = "/"

non_us_pound = "•"

[broot]


[micro]


[helix]
