[micro]
home = "Home"
end = "End"
page_up = "PageUp"
page_down = "PageDown"


up_arrow = "Up"
down_arrow = "Down"
left_arrow = "Left"
right_arrow = "Right"


O = "Alt"
E = "Alt"
T = "Ctrl"
W = "Ctrl"
S = "Shift"
R = "Shift"


spacebar = "Space"

[helix]
home = "home"
end = "end"
page_up = "pageup"
page_down = "pagedown"


up_arrow = "up"
down_arrow = "down"
left_arrow = "left"
right_arrow = "right"


O = "A"
E = "A"
T = "C"
W = "C"
S = "S"
R = "S"


spacebar = "space"
delete_forward = "del"
delete_or_backspace = "backspace"
escape = "esc"
